### PR TITLE
Replace Travis CI with Github Actions

### PR DESCRIPTION
**Pull request by madskjeldgaard**
This PR replaces Travis CI with Github Actions to automatically build the plugin produced by this recipe. 

For more information about this workflow: https://madskjeldgaard.dk/posts/how-to-gh-action/

PS. the .yml file is ugly as hell, since Jinja needs to escape all double curly braces with double curly braces, so it's basically a curly brace Inception type situation but it works.

I tried creating a plugin repo with this and running the build and it works for me.

### CODE REVIEW

**Comment by madskjeldgaard** [comment]
Sorry, I forgot to escape the github token stuff, I fixed it now and tested again and it looks good. Sorry about that.

**Comment by madskjeldgaard** [comment]
@dyfer or someone else - could you have a look a this when time permits?

**Comment by dyfer** [comment]
Thanks! 
Not a full review, but on the first glance:
- I'm not sure if you need to use separate windows and unix steps in most cases - using bash under windows allows for using unix-style paths and things generally work fine, aside from specific situations (esp related to env variables)
- I'd prefer if check for the tag is performed manually instead of pulling in a special action (I think it's something as simple as like `if: startsWith(github.ref, 'refs/tags/')`)
- as for draft release parameter I feel like that should either be set to false, or somehow configurable. E.g. if you need/want to sign binaries after they're uploaded, or change description etc, it's useful to first publish a draft release. This is what we do in SC. And if you make it configurable, then maybe prerelease could also be settable?
- in SC we use action softprops/action-gh-release for the release. Have you compared the two? Are there advantages to one over the other?

**Comment by madskjeldgaard** [comment]
> Thanks! 
> Not a full review, but on the first glance:
> - I'm not sure if you need to use separate windows and unix steps in most cases - using bash under windows allows for using unix-style paths and things generally work fine, aside from specific situations (esp related to env variables)
> - I'd prefer if check for the tag is performed manually instead of pulling in a special action (I think it's something as simple as like `if: startsWith(github.ref, 'refs/tags/')`)
> - as for draft release parameter I feel like that should either be set to false, or somehow configurable. E.g. if you need/want to sign binaries after they're uploaded, or change description etc, it's useful to first publish a draft release. This is what we do in SC. And if you make it configurable, then maybe prerelease could also be settable?
> - in SC we use action softprops/action-gh-release for the release. Have you compared the two? Are there advantages to one over the other?

This is great. Thank you - I will go over these in detail soon

**Comment by dyfer** [comment]
@madskjeldgaard I'm working on adding github actions for sc3-plugins, using your PR as inspiration. It's totally fine if we have somewhat different approaches, but there are few more things that came to my mind:
- it's probably to use `if: runner.os == 'Windows'` for OS check, instead of `matrix.os`, which version might change
- we can use the checkout action instead of calling `git clone`, but that's just a matter of preference
- `actions/create-release` is not maintained anymore; but maybe we don't even need it? Won't `svenstaro/upload-release-action` just create a release if needed?
- `7z` is already available on Windows for zipping
- so far we provide both 32-bit and 64-bit builds of SC on Windows; might be desirable to have both being build?
- for plugins using FFTW, one needs to install it as well

More to come, I'm still working on this...

EDIT: FFTW might be out of scope for this, OTOH it's probably something to document...

**Comment by madskjeldgaard** [comment]
> @madskjeldgaard I'm working on adding github actions for sc3-plugins, using your PR as inspiration. It's totally fine if we have somewhat different approaches, but there are few more things that came to my mind:
> 
>     * it's probably to use `if: runner.os == 'Windows'` for OS check, instead of `matrix.os`, which version might change
> 
>     * we can use the checkout action instead of calling `git clone`, but that's just a matter of preference
> 
>     * `actions/create-release` is not maintained anymore; but maybe we don't even need it? Won't `svenstaro/upload-release-action` just create a release if needed?
> 
>     * `7z` is already available on Windows for zipping
> 
>     * so far we provide both 32-bit and 64-bit builds of SC on Windows; might be desirable to have both being build?
> 
>     * for plugins using FFTW, one needs to install it as well
> 
> 
> More to come, I'm still working on this...
> 
> EDIT: FFTW might be out of scope for this, OTOH it's probably something to document...

That's fantastic Marcin. Thank you! I'm finally back from my summer holiday so I can update this PR soon! (and will also update all my own repos using a similar runner to this to include your great suggestions).

**Comment by dyfer** [comment]
You're very welcome, Mads!
For reference, here's my proposed [yaml file](https://github.com/supercollider/sc3-plugins/pull/320/files#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8) for sc3-plugins, taking yours as a framework. As I wrote earlier, FFTW parts (Linux deps, vcvars etc) can be probably left out; as for building triggers, that's something to discuss further (I'm fine with just building on tags for cookiecutter). Linux, macOS, Win32 and win64 builds are provided. Note that deployment is done with only one action.

**Comment by dyfer** [comment]
Here's the current sc3-plugins [GH Actions file](https://github.com/supercollider/sc3-plugins/blob/main/.github/workflows/CI.yml) - There is one change from the one linked previously: on macOS XCode version and deployment target are specified.

**Comment by madskjeldgaard** [comment]
Alright @dyfer  I think we are ready for another review. First of all sorry for the extremely slow responsiveness - there's been a bit too much above this one on the to do list but I should have addressed most of your really good suggestions now (which also seems to have made it a lot faster among other things).

I could not get the sc3 way of zipping things to work so I've stuck with this for now. (and I cannot get 7z to run in powershell without installing it first). Sorry for being a newb about the windows stuff - I am pretty clueless when it comes to windows.

I've set it to prelease by default (good idea!). 

The sc3 plugins yaml file is great - and served as an inspiration here again. 

I tried creating a new project with the template after finishing the edits and it seems to work properly.

**Comment by madskjeldgaard** [comment]
PS. I don't have a whole lot more brain space to work on this for a while FYI but will of course make changes if necessary :)

**Comment by dyfer** [comment]
Thanks @madskjeldgaard !

I'd really like to have the configure and build scripts be the same for all platforms - it should work as is in bash.
If you'd like to have zipping as separate steps for Windows and *nix it's fine, but if you switch Windows to bash I think you won't need to install 7z (see sc3-plugins yaml).
Finally, the build directory could be set as an environment variable so that it's not hardcoded in all the steps.

Let me know if you can make these changes or if you'd like me to submit a PR against your branch :)

**Comment by madskjeldgaard** [comment]
If you feel like doing a PR against this that would be awesome ! Thanks again

**Comment by dyfer** [comment]
I've submitted a PR against your branch: https://github.com/madskjeldgaard/cookiecutter-supercollider-plugin/pull/1

**Comment by madskjeldgaard** [comment]
It all looks good. I just tried making a repo using it and build went fine. A superficial inspection of the zip files produced seems good. The linux one contains .so files and windows and mac versions contain .scx.

**Comment by madskjeldgaard** [comment]
So I think we can merge this now @dyfer

**Comment by dyfer** [comment]
Thanks!

**Pull request merged**
